services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: OnlineShopSample
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh --quiet"]
      interval: 1s
      timeout: 2s
      retries: 5

  online_shop_sample:
    image: local/online-shop-sample:latest
    container_name: online_shop_sample
    ports:
      - '4000:8080'
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGODB__CONNECTIONSTRING: mongodb://mongodb:27017
      MONGODB__DATABASENAME: OnlineShopSample
      ASPNETCORE_ENVIRONMENT: Development
      ENABLEDATASEED: 'True'